### ISSUE TITLE
[Android] [BC] org.bouncycastle.cms.CMSException: Could not create DES cipher

### ISSUE THREAD

**Issue by demitsuri** [jscep/jscep#24]
I've got the following exception while performing SCEP workflow in my android application:

```
E: org.jscep.transaction.TransactionException: org.jscep.message.MessageDecodingException: org.bouncycastle.cms.CMSException: Could not create DES cipher
E:  at org.jscep.transaction.EnrollmentTransaction.send(EnrollmentTransaction.java:123)
E:  at org.jscep.client.Client.send(Client.java:680)
E:  at org.jscep.client.Client.enrol(Client.java:635)
E:  at app.task.SecondPhaseTask.doScep2(SecondPhaseTask.java:478)
E:  at app.task.SecondPhaseTask.doInBackground(SecondPhaseTask.java:169)
E:  at app.task.SecondPhaseTask.doInBackground(SecondPhaseTask.java:1)
E:  at android.os.AsyncTask$2.call(AsyncTask.java:264)
E:  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E:  at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E:  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
E:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E:  at java.lang.Thread.run(Thread.java:856)
E: Caused by: org.jscep.message.MessageDecodingException: org.bouncycastle.cms.CMSException: Could not create DES cipher
E:  at org.jscep.message.PkcsPkiEnvelopeDecoder.decode(PkcsPkiEnvelopeDecoder.java:95)
E:  at org.jscep.message.PkiMessageDecoder.decode(PkiMessageDecoder.java:163)
E:  at org.jscep.transaction.Transaction.decode(Transaction.java:107)
E:  at org.jscep.transaction.EnrollmentTransaction.send(EnrollmentTransaction.java:121)
E:  ... 12 more
E: Caused by: org.bouncycastle.cms.CMSException: Could not create DES cipher
E:  at org.jscep.message.PkcsPkiEnvelopeDecoder$InternalKeyTransEnvelopedRecipient.getRecipientOperator(PkcsPkiEnvelopeDecoder.java:134)
E:  at org.bouncycastle.cms.KeyTransRecipientInformation.getRecipientOperator(Unknown Source)
E:  at org.bouncycastle.cms.RecipientInformation.getContentStream(Unknown Source)
E:  at org.bouncycastle.cms.RecipientInformation.getContent(Unknown Source)
E:  at org.jscep.message.PkcsPkiEnvelopeDecoder.decode(PkcsPkiEnvelopeDecoder.java:91)
E:  ... 15 more
E: Caused by: java.security.InvalidKeyException: DES key too long - should be 8 bytes
E:  at com.android.org.bouncycastle.jce.provider.JCEBlockCipher.engineInit(JCEBlockCipher.java:570)
E:  at javax.crypto.Cipher.init(Cipher.java:616)
E:  at javax.crypto.Cipher.init(Cipher.java:566)
E:  at org.jscep.message.PkcsPkiEnvelopeDecoder$InternalKeyTransEnvelopedRecipient.getRecipientOperator(PkcsPkiEnvelopeDecoder.java:132)
E:  ... 19 more
```

As you can see, there is something wrong with deciphering. 

I saved server response and tried to parse it directly (by copypasting jscep code in my test desktop java app on Oracle's JVM)... and it was parsed well. But when I change provider to Bouncy Castle (add second parameter "BC" here - https://github.com/demitsuri/jscep/blob/master/src/main/java/org/jscep/message/PkcsPkiEnvelopeDecoder.java#L153), bug appears again.

It seems to be that Oracle and Bouncy Castle implementation have different default parameters for RSA cipher. I discovered from OpenJDK, that Oracle's default RSA transformation is "RSA/ECB/PKCS1Padding".

Android have Bouncy Castle implementation of used java api. So, for the compatibility we should explicitly define RSA transformation as "RSA/ECB/PKCS1Padding".

**Comment by pauldavidgilligan-msm** [comment]
Hello I am now getting this error too, using bcpkix-jdk15on 1.51 with current release:

{{{
Caused by: java.security.InvalidKeyException: Unwrapping failed
	at com.sun.crypto.provider.RSACipher.engineUnwrap(RSACipher.java:447)
	at javax.crypto.Cipher.unwrap(Cipher.java:2466)
	at org.jscep.message.PkcsPkiEnvelopeDecoder$InternalKeyTransEnvelopedRecipient.unwrapKey(PkcsPkiEnvelopeDecoder.java:155)
	at org.jscep.message.PkcsPkiEnvelopeDecoder$InternalKeyTransEnvelopedRecipient.getRecipientOperator(PkcsPkiEnvelopeDecoder.java:130)
}}}

**Comment by seize-the-dave** [comment]
@pauldavidgilligan-msm can you open a new issue please?
