### ISSUE TITLE
Failed to read PKIOperation message from MacOS

### ISSUE THREAD

**Issue by dveyarangi** [jscep/jscep#35]
Hi,

PKIOperation fails when the protocol is initiated by scep configuration profile on mac os, with following exception:

SEVERE: Servlet.service() for servlet [RA] in context with path [/scep-ra] threw exception [org.bouncycastle.cms.CMSException: IOException reading content.] with root cause
java.io.IOException: corrupted stream - out of bounds length found
        at org.bouncycastle.asn1.ASN1InputStream.readLength(Unknown Source)
        at org.bouncycastle.asn1.ASN1InputStream.readLength(Unknown Source)
        at org.bouncycastle.asn1.ASN1InputStream.readObject(Unknown Source)
        at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
        at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
        at org.bouncycastle.cms.CMSSignedData.<init>(Unknown Source)
        at org.jscep.server.ScepServlet.service(ScepServlet.java:188)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at forescout.portal.state.servlet.FSServletFilter.doFilter(FSServletFilter.java:43)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)

Following is the request body:

 /scep-ra/pki?operation=PKIOperation&message=MIIKRQYJKoZIhvcNAQcCoIIKNjCCCjICAQExDzANBglghkgBZQMEAgMFADCCBLwGCSqGSIb3DQEHAaCCBK0EggSpMIIEpQYJKoZIhvcNAQcDoIIEljCCBJICAQAxggGyMIIBrgIBADCBlTB+MRMwEQYKCZImiZPyLGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJZm9yZXNjb3V0MRMwEQYKCZImiZPyLGQBGRYDbGFiMRowGAYKCZImiZPyLGQBGRYKbmV0d29ya2luZzEbMBkGA1UEAxMSbmV0d29ya2luZy1OREMzLUNBAhMbAAACf+OD9O3ZJvDcAAAAAAJ/MA0GCSqGSIb3DQEBAQUABIIBABt+j+k6Deo0ALc2nc5zdMbjZADwL/5NHarWsaPZnCzxxUg1qyrDE5Ke5cq1BuSMSei49GE9d89YFhiIeDT0YS8Rr9Ax3bCW9lsDWUlgNF6vh7MCAPK7+prSy8zmQesxK/CVTISgXjQmXBkkwRv90fCURmi2uqv/cmVMgndVNa19r6zeyRnSbxNYyghWXW6uJhSRZjnWo9ktsdKiigHUqAcGkV0sQPFcC/hqJlm12oHtR3BJyIrQ8L99EXhS61j4066na15IqLvrDNvF7iwUMoqtbCLAlJZ9oXH4qCrbnu9lza+B7nTajFEf+9WX1th30urI6vtOqwcg14YWcX2p7KkwggLVBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECMxh/aBhqbQQgIICsF1TA8kbhvX7Bi5d/pUyejE0cTdrSU7HNzSu7z618hGu88II7dl3BKe3cS5tc9ffTLsNaPVME43Ia4ySsN9Eqs9K/K83pH5rkezOlM5lofrXIt5yY/rirwsjPrhkiXi9PrUa4XWXP7+6qag6uylrdWhyW/LGTJsNglp0dhnbl46773/Xybk8UFMM9fjQtBbyYPmuCNvAZvzl/fDNYPfi8x4QmwChcIo5Ul77I4G+Etg3xpavoasG1X98gDmHD4jaczVEp7AVBe6yQ+lbqHqEkZ7PnLanxw9j6++ghw+VRke48Vdw44P3Fd2F25jObGQ1fsnMRfBflnjkiPke0s5kahPLcLlaxFDyB8AaF6NB8lHX4tO2NFvTGO2+wSToGYqVeN02+l+ybgw5Cqr/mv9KeiYWyLau2gdW/00+eO5eA8q7pJ/uz8P0KpLsf9iYT9bqVKr+R1B508laN+IU9EtQikdfeUH/MYP6c68DHUH1jC2XFhxyY+onQJk268AJM1Vyg7aA0proqK4qdOwQQA/T7E6aXn/+ieXwno0GHZd2SivQ4K2OqRpjytx6P03SWtP0/+DWAMCyxCIasB7WX7OwSjTRrY8/8E3/acC266p98bFpn8X9vIFqAKn2d1pbTIEWFbNkR1VPkyj9JglgeRxqDQ2sCCtK/xGqrWVNSBCf5CvY+B61Ukcj9HF0SdOBqgTyrkZgy4ku5QLmUy2K1XEoI80xHX3qwc5/ljbKYo/4dMnCgXFqIL4T+wcgQTFbbPFiafOao9uxfJtDMjjIHM/gCI0DrerUmr+mwsg5QZWkBGyeF5pZdqutYBEAFUCvlHQEnLkjriFEzw1qVHD0crHCaxxuSUBsdG4zxUA6BqAcAwPDmTG4ZiVzNfLkziG91hD6k03QKW+EqnJAaetD5kB1256gggL1MIIC8TCCAdmgAwIBAgIBATALBgkqhkiG9w0BAQswJzEYMBYGA1UEAwwPTURNIFNDRVAgU0lHTkVSMQswCQYDVQQGEwJVUzAeFw0xNTAzMzEwOTUxNTJaFw0xNjAzMzAwOTUxNTJaMCcxGDAWBgNVBAMMD01ETSBTQ0VQIFNJR05FUjELMAkGA1UEBhMCVVMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCrq5IhB+jDpnhpXjWfXZ8YkcMlQqFiAurJdEsW+vx6GMhYp4tyqpW2DyYuXBnN8X0t2Q7Whdt1BIsEJbmF7cDSPbjj73TS0gvqPm+gP97HKlivA9jl9ayaL7KfC3fkYh25rRqtKHFSwwBVwsYOlG+0QT/lpFKDQyCvMQTYihS2KDGPSpuPV9PtTQ7J+HNrQf03BuquPrM8X8QlSVZFa4qIgIs3LxknrPEH/Jr/lA8lFGjoNiMj1eodDdcz7CLwhycVx0PaLuIdPvszRYo8I89v5ggnUMEckzf5fwfkr6ItdkvV+DddwsajrXdyTUDku6wnfDapgXhjimUOdej7wOiTAgMBAAGjKjAoMA4GA1UdDwEB/wQEAwIHgDAWBgNVHSUBAf8EDDAKBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEAjmKYoMe9VOqaEkr7waj5j+rxFz9bhGoc5f3fwZbuoL1dLSuBVqQpPzwZ/Tagv8VFIH2yuHpPKdlFTARMigOrYIhsZXqzhrEBJKFCs8teEchj7Fu/HuDEWnZVjf/t8zcVQMdIRs+o3Zy9nKvDm3177JXurr4QAq/t1bht4E8wHTu0eS5Z/sbYfIx1gv55TqMuWNr7k8nsIgV+/Qhv7o9FlUNobUNuRha2I4Vm4WPzSM2mhoWV5EmAn/QatcMOZ+oenBOlCwcg4cedBd2fNHKMLi1Cfp/VhBfIO9/ntj9jrvFkAQSCgb9/KSW26qzh3XGNSGbZdorKs/idBAFIQfIiozGCAmEwggJdAgEBMCwwJzEYMBYGA1UEAwwPTURNIFNDRVAgU0lHTkVSMQswCQYDVQQGEwJVUwIBATANBglghkgBZQMEAgMFAKCCAQYwEgYKYIZIAYb4RQEJAjEEEwIxOTATBgkqhkiG9w0BCQcxBhMEYWFhYjAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBgGCmCGSAGG+EUBCQUxCgQI5wI1xV8Zyu8wHAYJKoZIhvcNAQkFMQ8XDTE1MDMzMTA5NTE1MlowOAYKYIZIAYb4RQEJBzEqEyhCMTAyRTM3RUVDMURBMjQzNzU4RkI3NEExNjRGMjdEMzQxRjc5MzJCME8GCSqGSIb3DQEJBDFCBEAqfjAxdyJ6W2tVkaqFdd3VQS0pbwTbZs5pMzmJPmQflv/OzZUNdw05Bj8Hk0Ku5eUcVtPP0Ym/xwetD3pDgjokMA0GCSqGSIb3DQEBAQUABIIBAHZ14xA0d6mA8n2rZZh+vNfAC/7Yj6i5X0QO0Pv+w0079GNYgIf5ymSPJLp9vxr92Or7q07TcllCam3H+0XQ+tT1NMM/8zMzWubJLdApIYIOUqCXEGfiQ6FjR903NE7JanebdUxPGc/NvJ+YVIhCpbXUXveFxNHOvO5coYCZ7V4W2sbCIQu9y1rxtJpuHd2jVRi93vvlZURtksqcXlyp+IR8obwXf35TqplNjTfQamg0v6oeIK0A80VqSYb9tXf0KRBKrCj9JGabhECCorxHwaDAYihAUgS5NLoULBwWHNVtEeA4x2ye3kvH1QIGyg6+slL5Rmjt+2QOAoyyhto7FHI= HTTP/1.1" 500 2763

Whats strange is that the same configuration works with iOS devices.

Any lead would be appreciated )

**Comment by seize-the-dave** [comment]
@dveyarangi what version of jscep are you using?

**Comment by dveyarangi** [comment]
2.1.0

**Comment by seize-the-dave** [comment]
@dveyarangi can you confirm this is still an issue in 2.2.0 please?

**Comment by dveyarangi** [comment]
yes, still an issue, with bouncy 1.51 and jscep 2.2.0

**Comment by dveyarangi** [comment]
Ugh, just a note, it took me an effort to discover this, and i'm not sure where to put this - for GetCACert to work with mac scep client, scep registration authority has to return 3 certificates - CA, and two RA, one marked for CEP encryption and the other for EnrollmentAgentOffline

**Comment by seize-the-dave** [comment]
Thanks @dveyarangi.  I think configuration to support a particular SCEP client is beyond the scope of jscep, but it might be worth writing a blog post if you're so inclined. :smile:

**Comment by seize-the-dave** [comment]
This issue appears to be that the byte string length is too long.  Can you enable debug logging on the server and add the log to this issue please?

**Comment by seize-the-dave** [comment]
Also, did you enable HTTP POST in `doCapabilities()`?

**Comment by seize-the-dave** [comment]
I wrote a test case here:

https://github.com/jscep/jscep/blob/issue-35/src/test/java/org/jscep/server/Issue35Test.java

**Comment by dveyarangi** [comment]
Hey, sorry for the delay.
HTTP POST capability fixed this. I had removed it initially, because I wanted jscep responses to be as close as possible to MSCEP to understand my earlier problems.
Thanks!

**Comment by rajeshkarthik** [comment]
hello all,

 I am really sorry if I am too late into discussion, but of late am facing an identical issue when I am trying SCEP enrolment with Mac. The error is same as above but it seems like am using JSCEP server with POST enabled. can you please help me out?

**Comment by seize-the-dave** [comment]
Hi @rajeshkarthik, this issue is closed.  If you are running into the same problem please can you create a new issue, complete with logs, etc?
