### ISSUE TITLE
PKIOperation - IOException - Mac OSX 10.10.3

### ISSUE THREAD

**Issue by rajeshkarthik** [jscep/jscep#39]
Hello

 I am trying to enrol for a certificate with a jscep server and Mac native OSX client - I keep getting error (-603) on the client side. The server side logs suggest that it was an IOException content longer than expected.

```
javax.servlet.ServletException: org.bouncycastle.cms.CMSException: IOException reading content.
        at org.jscep.server.ScepServlet.service(ScepServlet.java:195)

Caused by: org.bouncycastle.cms.CMSException: IOException reading content.
        at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
        at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
        at org.bouncycastle.cms.CMSSignedData.<init>(Unknown Source)
        at org.jscep.server.ScepServlet.service(ScepServlet.java:193)
        ... 22 more
Caused by: java.io.IOException: corrupted stream - out of bounds length found
        at org.bouncycastle.asn1.ASN1InputStream.readLength(Unknown Source)
        at org.bouncycastle.asn1.ASN1InputStream.readLength(Unknown Source)
        at org.bouncycastle.asn1.ASN1InputStream.readObject(Unknown Source)
        ... 26 more
```

**Comment by seize-the-dave** [comment]
Can you provide logs too please?

**Comment by rajeshkarthik** [comment]
I have pasted the message that I see on the server side. Could you please tell me which logs you are looking for?

**Comment by seize-the-dave** [comment]
You should be able to configure log4j to get a trace of what jscep is doing.  See the following file for an example:

https://github.com/jscep/jscep/blob/master/src/test/resources/log4j.properties

**Comment by rajeshkarthik** [comment]
I tried the TRACE logging but am not seeing any more logs than the above logs. I am feeling like to totally stuck. could you please look into this

**Comment by rajeshkarthik** [comment]
Got this resolved by supporting POST. Thanks for your help
