### ISSUE TITLE
Certificate renewal issue java.security.SignatureException: Signature length not correct: got 512 but was expecting 128

### ISSUE THREAD

**Issue by gcamus** [jscep/jscep#55]
Hi @seize-the-dave 

We have an issue when we try to renew a certificate. 

We obtain the following exception :

> org.bouncycastle.operator.RuntimeOperatorException: exception obtaining signature: Signature length not correct: got 512 but was expecting 128

The problem appears because when we renew, we use the issued certificate from CA which has signed the certificate with a stronger  

See PR #54
Stacktrace :
Caused by: org.bouncycastle.operator.RuntimeOperatorException: exception obtaining signature: Signature length not correct: got 512 but was expecting 128
	at org.bouncycastle.operator.jcajce.JcaContentVerifierProviderBuilder$SigVerifier.verify(Unknown Source)
	at org.bouncycastle.cert.X509CertificateHolder.isSignatureValid(Unknown Source)
	at org.jscep.client.Client.isSelfSigned(Client.java:643)
	... 32 more
Caused by: java.security.SignatureException: Signature length not correct: got 512 but was expecting 128
	at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:189)
	at java.security.Signature$Delegate.engineVerify(Signature.java:1172)
	at java.security.Signature.verify(Signature.java:623)
	at org.bouncycastle.operator.jcajce.JcaContentVerifierProviderBuilder$SignatureOutputStream.verify(Unknown Source)
	... 35 more

**Comment by gcamus** [comment]
See PR #54
